var aboutMe = {
	question1: "1. What is your name? ",
	name: "Brandee Ogunjobi",
	question2: "2. What is your chat user name & host?",
	userName: "brandeeogunjobi and Google Hangouts",
	question3:"3. In which time zone do you reside?",
	timeZone: "MST - Arizona",
	question4:"4. Why are you in the Mobile Dev Program?",
	explanation: "To advance my career.",
	question5:"5. How comfortable are you in JS?",
	javaComfort: "I am somewhat comfortable with Javascript.",
	question6:"6. How comfortable are you with Titanium?",
	titaniumComfort: "I am somewhat comfortable with Titanium.",
	question7:"7. What is your favorite food?",
	favFood: "Fried Tacos",
	question8: "8. What is your favorite color?",
	favColor: "Grey",
	question9:"9. What is your favorite sport?",
	favSport: "Kids Soccer",
	question10:"10.	Do you have a family? (ages, gender)",
	familyDesc: "I am married with five children. My oldest son is 21 Johnny, Tyelerr 19, Joseph 6, Joshua 4, Bennett 2. ",
	question11:"11.What kind of work do you do?",
	work: "Marketing Executive"
};
